### ISSUE TITLE
[feature] 숙소 예약/결제 기본 기능 구현

### ISSUE THREAD

**Issue by silxbro** [codesquad-masters2024-airdnb-team12/be-airdnb#12]
## 🔥 Feature Issue
- 숙소 예약 관련 기본 기능을 구현합니다.
- 결제 관련 기본 기능을 구현합니다.

## ✅ TODO
 - [x] 숙소 예약 관련 기능
   - [x] 숙소 예약 생성
   - [x] 숙소 예약 내역 조회
   - [x] 숙소 예약 상세 조회
   - [x] 숙소 예약 승인, 거절, 취소 기능
   - [x] 숙소 이용 현황 업데이트 스케줄링
 - [x] 결제 관련 기능
   - [x] 결제 금액 계산
   - [x] 결제 내역 조회
   - [x] 결제 상세 조회

## 🎸 ETC
- 숙소 예약 및 결제 내역 조회 시, 호스트/게스트, 상태코드 분류를 적용합니다.
- 숙소 예약 및 결제 상세 조회 시, 호스트/게스트 권한 검증을 수행합니다.
- 숙소 예약의 이용 현황 업데이트 스케줄링은 매일 체크인(15:00), 체크아웃(11:00) 시간에 실행됩니다.
- 결제 금액 계산 시, 수수료 및 할인 정책의 기준 시점은 결제 시점으로 적용합니다.
