### ISSUE TITLE
[feature] TourApi에서 제공하는 한국 숙박업소 데이터 DB에 저장

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-airdnb-team12/be-airdnb#7]
## 🔥 Feature Issue
- [TourApi 4.0](https://api.visitkorea.or.kr/) 에서 제공하는 한국 숙박업소 데이터 엑셀 파일을 python을 이용해 mysql DB에 저장합니다.
- 일부 데이터는 테이블 구조에 맞게 값을 랜덤 생성해 초기화합니다.

## ✅ TODO
 - [x] 숙소 등록을 위한 mock 사용자 등록
 - [x] xls 파일 파싱해 DB에 데이터 저장
 - [ ] 이미지url 등록
 - [x] facility, accommodationInfo도 등록

**Comment by sharpie1330** [comment]
AccommodationInfo는 선택정보이기에 삽입하지 않았습니다.
이미지 url 등록은 s3 연결에 성공 시 추가적으로 구현합니다.
