### ISSUE TITLE
[feature] 숙소 목록조회, 상세조회, 수정, 삭제 기본 RUD 구현

### ISSUE THREAD

**Issue by sharpie1330** [codesquad-masters2024-airdnb-team12/be-airdnb#9]
## 🔥 Feature Issue
숙소 도메인에 대한 조회, 수정, 삭제 기능을 개발합니다.

## ✅ TODO
 - [ ] 숙소 목록 조회 (일단 findAll)
 - [ ] 숙소 상세 조회
 - [ ] 숙소 수정
 - [ ] 숙소 삭제
 - [ ] 테스트 코드 작성

**Comment by sharpie1330** [comment]
잘못된 커밋 이력 문제로 해당 이슈는 닫습니다.
